### PR TITLE
FIX: Update values in QueueProcessor

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
Changes related to bootstrap list are now obsoleted by the actual bootstrap list management. Though the change in `_AccountAuthManager.lookupAccountAttributes()` is still valid. Can you update the PR to keep this change only?

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Pull request merged**
