### PR TITLE
improvement/S3C-2367 migrate package manager to yarn

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Migrate package manager to yarn

**Which issue does this PR fix?**
fixes #S3C-2367

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
test

**Comment by Katherinelaue1** [comment]
ping

**Comment by Katherinelaue1** [comment]
test

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
test

**Comment by Katherinelaue1** [comment]
ping

**Comment by Katherinelaue1** [comment]
@bert-e status

**Comment by anurag4DSB** [comment]
@bert-e force_reset

**Comment by anurag4DSB** [comment]
@bert-e wait

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Review by nicolas2bert — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Comment by anurag4DSB** [comment]
@bert-e status

**Review by bennettbuchanan — APPROVED** [review]

**Pull request merged**
