### PR TITLE
bugfix: ZENKO-2560 S3C Regression1.2.0 RC4

### PR DESCRIPTION
**Pull request by naren-rajendran**
S3C Backbeat Regression 1.2.0 RC4. Reverted the last commit.

### CODE REVIEW

**Review by jonathan-gramain — CHANGES_REQUESTED** [review]
To help tracking, the commit message should contain the commit hash that is being reverted.

Just issuing `git revert commit-hash(es)-to-revert` should add this info to the commit messages automatically.

**Comment by naren-rajendran** [comment]
@bert-e  reset

**Comment by rahulreddy** [comment]
I think the commit message (you fixed the commit body) needs to reflect the change it's reverting, just using the message from previous commit and appending it with `revert:` should be sufficient

**Comment by naren-rajendran** [comment]
@bert-e reset

**Review by rahulreddy — APPROVED** [review]

**Review by jonathan-gramain — CHANGES_REQUESTED** [review]
The commit message says:

```
Reverted to a8e10d5.
revert: improvement:ZENKO-2262 Start OOB in paused state
```

But:

```
git diff --stat a8e10d5 0d19872
 .eslintrc                                               |   9 ++++-
 eve/main.yml                                            |  10 ++---
 eve/workers/unit_and_feature_tests/Dockerfile           |  27 ++++++++++++-
 eve/workers/unit_and_feature_tests/run_ft_tests.bash    |   5 ++-
 extensions/mongoProcessor/MongoQueueProcessor.js        |   4 ++
 extensions/replication/queueProcessor/QueueProcessor.js |   4 +-
 extensions/replication/tasks/CopyLocationTask.js        | 111 +++++++++++++++++++++++++++++++++++------------------
 extensions/replication/tasks/MultipleBackendTask.js     | 149 ++++++++++++++++++++++++++++++++++++++++++++---------------------------
 extensions/replication/tasks/ReplicateObject.js         |  73 ++++++++++++++++++++++-------------
 lib/queuePopulator/IngestionReader.js                   |  16 +++++++-
 lib/queuePopulator/LogReader.js                         |   7 +++-
 package.json                                            |   2 +-
 tests/functional/ingestion/IngestionReader.js           |  61 ++++++++++++++++-------------
 tests/functional/ingestion/MongoQueueProcessor.js       |   2 +
 tests/functional/replication/streamedCopy.spec.js       | 309 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tests/functional/utils/MetadataMock.js                  |  21 ++++++----
 tests/unit/replication/MultipleBackendTask.js           |  22 +++++++----
 yarn.lock                                               |  23 +++++++----
 18 files changed, 669 insertions(+), 186 deletions(-)
```

Likely the changes are totally fine and revert what needs to be reverted, but IMHO it's important to have commit messages reflecting what they're actually doing. Why not simply doing a `git revert` of the commits that need to be reverted?

**Comment by naren-rajendran** [comment]
The only change made to fix the pause-resume error is to the file`bin/ingestion.js`. As requested I only reverted this file to it previous state, from the commit `a8e10d511dbba4901a5ff0d18f1790d8c39ab1bc`. May be the commit message to pr is not right, I will update the description to reflect that the change is only made to the file specified. The file difference above (from @jonathan-gramain comment) is because there were other commits pushed to this repository which did not modify the file `bin/ingestion.js`.

**Comment by naren-rajendran** [comment]
Closing this pr, as a new one was created and merged. The duplicate pr has addressed all the review comments and recommendations.

**Pull request closed without merging**
