### PR TITLE
bugfix: include passwords in redis configuration

### PR DESCRIPTION
**Pull request by JianqinWang**

### CODE REVIEW

**Comment by JianqinWang** [comment]
@bert-e reset

**Review by rahulreddy — APPROVED** [review]

**Review by philipyoo — APPROVED** [review]

**Comment by JianqinWang** [comment]
@bert-e approve

**Comment by rahulreddy** [comment]
@bert-e bypass_author_approval

**Comment by JianqinWang** [comment]
@bert-e reset

**Pull request merged**
