### PR TITLE
Bugfix/zenko 3234/queue populator missing extensions

### PR DESCRIPTION
**Pull request by alexanderchan-scality**

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
wasn't quite sure why the `_loadExtensions` method was removed, so feel free suggest a more appropriate fix.

**Review by miniscruff — APPROVED** [review]

**Comment by naren-rajendran** [comment]
> wasn't quite sure why the `_loadExtensions` method was removed, so feel free suggest a more appropriate fix.

Looks like merge issue, https://github.com/scality/backbeat/commit/b368abf7a7a6d69eba132d1590be21a00f8844de#diff-86ebbb86433211b55c97d9a810d9741ba7f69b2704aa057a1955e7572b9a1ef3

@alexanderchan-scality  this is also missing in 8.1, same issue. Can you change the base back to 8.1?

**Review by naren-rajendran — APPROVED** [review]

**Pull request merged**
