### PR TITLE
bf S3C-4239 fixed log reader crash

### PR DESCRIPTION
**Pull request by naren-rajendran**
Updated arsenal to handle multiple calls of the same callback in the event of an error in reading raft logs.

### CODE REVIEW

**Review by jonathan-gramain — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e reset

**Review by miniscruff — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e help

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e status

**Comment by naren-rajendran** [comment]
@bert-e force_reset

**Pull request merged**
