### PR TITLE
Set dependencies to use hashs instead of rel/*-based tags.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
ping !

**Review by alxf — APPROVED** [review]

**Comment by ghost** [comment]
@jonathan-gramain It looks like Bert-E cannot make progress as development/7.4 is not contained in development/8.0.

This probably means that a few changes were made previously on rel/7.4 and never merged on development/8.0. There is a conflict that I am currently unable to solve.

The best advice @tcarmet and myself can provide is: Please create a PR targetting development/8.0, which forward-ports development/7.4 in there, before we can merge and close this one.

Thanks :)

**Comment by jonathan-gramain** [comment]
https://github.com/scality/backbeat/pull/366 should unblock this!

**Review by jonathan-gramain — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
@bert-e reset

**Pull request merged**
