### PR TITLE
FT: Support MPUs when part copied from MPU

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@electrachong Good idea. I think an Integration test would also help.

**Comment by bennettbuchanan** [comment]
Thanks for the feedback. I will add an Integration test for this case since it does depend on location objMD that is originally built in S3. 

Also, I believe we can assume that the locations MD of an MPU will be sequentially ordered by part number. I also think it is possible that S3 could be the one to build a location obj MD that suits our needs. At the moment, though, I am not sure how these location elements are being used, or if they can be modified. Such a change could help with optimization down the line.

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
I don't think Backbeat is enabled on ultron. Let me do that change.

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
E2E passed with master, and Integration tests using uploadCopyPart.
* http://ci.ironmann.io/gh/scality/Integration/14443
* http://ci.ironmann.io/gh/scality/Integration/14439

I've now pushed unit tests but have not altered the lib code.

**Comment by bennettbuchanan** [comment]
@ironman-machine 
try

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Pull request merged**
