### PR TITLE
S3C-2034: bump ioredis version

### PR DESCRIPTION
**Pull request by JianqinWang**
dependent on https://github.com/scality/Arsenal/pull/795

### CODE REVIEW

**Review by nicolas2bert — APPROVED** [review]

**Comment by JianqinWang** [comment]
@bert-e reset

**Comment by JianqinWang** [comment]
@bert-e reset

**Comment by JianqinWang** [comment]
@bert-e reset

**Comment by JianqinWang** [comment]
@bert-e reset

**Comment by JianqinWang** [comment]
@bert-e reset

**Review by tmacro — APPROVED** [review]

**Comment by JianqinWang** [comment]
@bert-e reset 😡 stop trying to be so smart and let me make the correct fixes

**Comment by JianqinWang** [comment]
@bert-e help

**Review by rahulreddy — APPROVED** [review]

**Comment by JianqinWang** [comment]
@bert-e approve

**Pull request merged**
