### PR TITLE
use ObjectMD class

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Depends on Arsenal PR https://github.com/scality/Arsenal/pull/326

cleanup: use ObjectMD class for QueueEntry helper
    
Since QueueEntry is essentially holding metadata from the entry, plus
a few additional info, make it inherit from ObjectMD so we get access
to all its getters/setters directly.
    
Also use ObjectMDLocation class to manipulate location info.

Most helpers removed from QueueEntry have been moved to Arsenal ObjectMD/ObjectMDLocation.

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_BACKBEAT_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by jonathan-gramain** [comment]
Saw a few issues with tests that need investigation (empty object)

**Comment by jonathan-gramain** [comment]
Tests are passing now (previous issues with empty object) but would like to confirm with manual tests that everything is alright before considering merging.

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by rahulreddy** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=ft/S3C-760-objectMDImportFromBlob
try

**Comment by rahulreddy** [comment]
@ironman-machine clean r=d7798110b0fcf821eb555222d782181724978171

**Comment by rahulreddy** [comment]
@ironman-machine r- r=d7798110b0fcf821eb555222d782181724978171

**Comment by rahulreddy** [comment]
@ironman-machine r- r=d7798110b0fcf821eb555222d782181724978171

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=ft/S3C-760-ObjectMDStorageClassGetter
try

**Pull request merged**
