### PR TITLE
Fwdport 7.2 to 7.4

### PR DESCRIPTION
**Pull request by jonathan-gramain**

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@ironman-machine r+

**Comment by jonathan-gramain** [comment]
@ironman-machine r- r+

**Comment by jonathan-gramain** [comment]
@ironman-machine r-

**Comment by jonathan-gramain** [comment]
@ironman-machine 
DEFAULT_BRANCH=rel/7.4
r+

**Comment by DavidPineauScality** [comment]
Maybe we didn't push integration's ultron/rel/7.4 branch when creating the rel/7.4 branch. Retry when you've pushed it, should work then.

**Comment by jonathan-gramain** [comment]
There is no rel/7.4 branch yet on Integration, that should explain. Shall I simply create it from the current master?

**Comment by jonathan-gramain** [comment]
+ ultron branch

**Comment by DavidPineauScality** [comment]
Yes. I'll do it today if it's not created yet.
I'll discuss that with @harperscality , I think she was unaware that this was a requirement for further development :)

**Comment by jonathan-gramain** [comment]
@ironman-machine r- r+

**Comment by jonathan-gramain** [comment]
Not needed anymore, done in #170.

**Pull request closed without merging**
