### PR TITLE
improvement: BB-58 apply probeserver config schema

### PR DESCRIPTION
**Pull request by naren-rajendran**
Apply probeserver configuration schema to backbeat extensions.

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Pull request merged**
