### PR TITLE
BB-7: update lifecycle object processor

### PR DESCRIPTION
**Pull request by alexanderchan-scality**

### CODE REVIEW

**Review by rachedbenmustapha — COMMENTED** [review]
LGTM overall but I'm not seeing credentials being retrieved in an asynchronous manner, if we were to benefit from auto-refresh through `.get()` to avoid intermittent auth failures.

**Comment by alexanderchan-scality** [comment]
@RachedBenMustapha please correct me if I am wrong. won't the service client object handle that logic at the time of performing the request? (I believe credentials are fetched for signing, and the `get()` async method would be called then)

**Review by rachedbenmustapha — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Pull request merged**
