### PR TITLE
Revert bugfix: ZENKO-2447 pause resume corrections

### PR DESCRIPTION
**Pull request by naren-rajendran**
This reverts commit da2a9da264c88181e0d3563e12ea1cca5ec988a8.

### CODE REVIEW

**Comment by naren-rajendran** [comment]
This is a new branch and pr for ZENKO-2560. I had to create this to have a cleaner commit log. I will remove https://github.com/scality/backbeat/pull/831 once this is approved.

**Review by rahulreddy — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e approve

**Comment by naren-rajendran** [comment]
@bert-e approve

**Review by jonathan-gramain — APPROVED** [review]

**Pull request merged**
