### PR TITLE
ft: S3C-1376 HTTPS support for backbeat replication

### PR DESCRIPTION
**Pull request by jonathan-gramain**
- allow optional use of HTTPS instead of HTTP to connect to remote
  nginx (port 9080), also make IAM route go through the proxy instead
  of port 8600 directly.

- make the configuration of certificates optional (not needed either for
  HTTP mode, or HTTPS without client certificate verification).

- more error messages in EchoBucket, add 'where' info to
  SetupReplication logs

- configure logging of vault clients managed by VaultClientCache to
  backbeat log level

- increase IAM timeout from 1s to 30s

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]
LGTM

**Review by philipyoo — APPROVED** [review]
lgtm 👍

**Comment by jonathan-gramain** [comment]
@bert-e wait

**Comment by jonathan-gramain** [comment]
@bert-e reset

**Comment by jonathan-gramain** [comment]
@bert-e reset

**Pull request merged**
