### PR TITLE
bf: abort destreq on error

### PR DESCRIPTION
**Pull request by philipyoo**

### CODE REVIEW

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
successes so far:
http://ci.ironmann.io/gh/scality/Integration/18459

ci fails are happening on `build-kafka` step..

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
@ironman-machine try

**Pull request closed without merging**
