### PR TITLE
bugfix: ZENKO-1606 Replicate tags from object PUT

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Depends on https://github.com/scality/cloudserver/pull/1774.

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]

**Review by rahulreddy — CHANGES_REQUESTED** [review]
Isn't passing the tags as a query param more efficient given that we don't have to parse it and query stringify again?

**Comment by bennettbuchanan** [comment]
@rahulreddy It is more efficient, however we're using a query string to determine the type of multiple backend operation to perform i.e. `operation=putobject`. There wouldn't be a way to distinguish the query param `operation` from a tag set. For example, if a user put a tag key of `operation` and value `cats` it would break the request.

I think that it probably should have been designed with this in mind, but we've been using the tags passed as stringified JSON in headers so I've just stuck with the current approach in that regard.

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
Ok makes sense, thanks. I think we need to revisit routing at some point.

**Review by jonathan-gramain — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
@bert-e approve

**Pull request merged**
