### PR TITLE
Skip objects with pending replication when expiring them

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Review by welansari — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e reset

**Review by benzekrimaha — APPROVED** [review]
LGTM

**Comment by nicolas2bert** [comment]
@bert-e approve

**Comment by nicolas2bert** [comment]
ping

**Comment by nicolas2bert** [comment]
@bert-e status

**Comment by nicolas2bert** [comment]
@bert-e help

**Comment by nicolas2bert** [comment]
@bert-e reset

**Comment by nicolas2bert** [comment]
@bert-e force_reset

**Pull request merged**
