### PR TITLE
Fwdport 7.2 to rel/7.4 (formerly master)

### PR DESCRIPTION
**Pull request by ThibaultRiviere**

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@ironman-machine r+

**Comment by jonathan-gramain** [comment]
@ironman-machine r-

**Comment by jonathan-gramain** [comment]
@ironman-machine r+

**Comment by jonathan-gramain** [comment]
@ironman-machine r-

**Comment by DavidPineauScality** [comment]
Suceeded at https://github.com/scality/Integration/pull/631#issuecomment-362599961

**Comment by DavidPineauScality** [comment]
Merging synchronously scality/bucketclient#128 scality/S3#1092 scality/MetaData#1317 scality/sproxydclient#136 scality/Arsenal#404 scality/backbeat#170 scality/Integration#631 , scality/Federation#1310

**Pull request merged**
