### PR TITLE
improvement: S3C-3602 minor improvements to kafka destination

### PR DESCRIPTION
**Pull request by naren-rajendran**
- kafka destination connection errors if any are logged now
- optional sasl mechanism for kerberos authentication type is set

### CODE REVIEW

**Review by tmacro — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e approve

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e approve

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e approve

**Pull request merged**
