### PR TITLE
feature: BB-50 Probe server should return undefined

### PR DESCRIPTION
**Pull request by miniscruff**
* Use sendError and sendSuccess from Arsenal

### CODE REVIEW

**Comment by naren-rajendran** [comment]
Ingestion processes now use the new probe server, these need the same treatment, https://github.com/scality/backbeat/pull/1938/files

**Review by naren-rajendran — COMMENTED** [review]
Ingestion processes now use the new probe server, these need the same treatment, https://github.com/scality/backbeat/pull/1938/files

**Comment by miniscruff** [comment]
> Ingestion processes now use the new probe server, these need the same treatment, https://github.com/scality/backbeat/pull/1938/files

Yea, after my change is merged you can do similar changes to your PR. Unless you think I should handle them.

**Comment by naren-rajendran** [comment]
> > Ingestion processes now use the new probe server, these need the same treatment, https://github.com/scality/backbeat/pull/1938/files
> 
> Yea, after my change is merged you can do similar changes to your PR. Unless you think I should handle them.

I think it should be with this PR because it would be easier to understand the changes, since they are all same across the processes.

**Review by naren-rajendran — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Pull request merged**
