### PR TITLE
FT: Support zero-byte object replication to AWS

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by bennettbuchanan** [comment]
E2E passed here: http://ci.ironmann.io/gh/scality/Integration/15805#build-parameters

**Pull request merged**
