### PR TITLE
backport: S3C-1643 node-rdkafka

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Backport the following commits from development/8.0:

* 67c8632b test: fix kafka bootstrap() mechanism
* 51a9c539 bf: switch to node-rdkafka
* 668fc631 [SQUASH ME] eve failed

Tied to Federation PR https://github.com/scality/Federation/pull/1599

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@bert-e wait

**Comment by jonathan-gramain** [comment]
@bert-e wait

**Review by philipyoo — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
@bert-e reset

**Comment by jonathan-gramain** [comment]
@bert-e wait

**Comment by jonathan-gramain** [comment]
@bert-e wait

**Comment by jonathan-gramain** [comment]
I successfully ran the core set of Integration backbeat tests (from curated branch test/runBackbeatTestsOnRealEnv) on two scality.cloud environments with one replicating to the other.

**Review by rahulreddy — APPROVED** [review]

**Pull request merged**
