### PR TITLE
impr: BB-361 update metric names

### PR DESCRIPTION
**Pull request by naren-rajendran**

### CODE REVIEW

**Review by nicolas2bert — COMMENTED** [review]
Note: dashboards and alerts would need to be updated for development/8.x branches.

**Review by nicolas2bert — APPROVED** [review]

**Comment by naren-rajendran** [comment]
> Note: dashboards and alerts would need to be updated for development/8.x branches.

Yes.. I will make changes in the integration branches.

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e help

**Comment by naren-rajendran** [comment]
@bert-e ping

**Comment by naren-rajendran** [comment]
@bert-e approve

**Pull request merged**
