### PR TITLE
Improvement/bb 263/blacklist2 hotfix

### PR DESCRIPTION
**Pull request by naren-rajendran**

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Comment by nicolas2bert** [comment]
ping

**Comment by nicolas2bert** [comment]
It seems to be some issue with`Command git rev-parse hotfix/7.10.5 returned with code 128: fatal: ambiguous argument 'hotfix/7.10.5':` from https://bert-e.scality.net/scality/backbeat

**Review by jonathan-gramain — APPROVED** [review]

**Pull request merged**
