### PR TITLE
ft: ZENKO-1343 use ingestion service account

### PR DESCRIPTION
**Pull request by philipyoo**

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by philipyoo** [comment]
@bert-e approve

**Comment by philipyoo** [comment]
@bert-e help

**Comment by philipyoo** [comment]
@bert-e reset

**Comment by philipyoo** [comment]
@bert-e force-reset

**Comment by philipyoo** [comment]
@bert-e force_reset

**Pull request merged**
