### PR TITLE
Backport 8.2 Lifecycle feature

### PR DESCRIPTION
**Pull request by rachedbenmustapha**
Preliminary backport of lifecycle code. Minimal set of changes required to have:
- lifecycle code
- working build
- linter passing
- unit tests passing
- feature tests passing

This code is not fully functional yet in S3C, as authentication method needs to be updated before functionality can be assessed.

### CODE REVIEW

**Review by alexanderchan-scality — COMMENTED** [review]
@RachedBenMustapha 
* since transition is being ported, should the `gc` extension be backported as well?
* the `lifecycle/objectProcessor` files are missing

**Comment by rachedbenmustapha** [comment]
@alexanderchan-scality missed the object  processor following a bad rebase, thank you.

About the gc, I was thinking that to keep changes small, it shouldn't be brought in since we're going to explicitly [not support](https://scality.atlassian.net/browse/S3C-4110?focusedCommentId=281591) transition policies.

**Review by jonathan-gramain — APPROVED** [review]

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by rachedbenmustapha** [comment]
ping

**Pull request merged**
